version: '2'
services:

  base-database:
    image: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
  base-application:
    build: .
    environment:
      - LOG_LEVEL=info
      - ZIPKIN_RECODER=console
      - SERVICE_PORT=9000
      - SERVICE_NAME=petstore
      - DATABASE_CLIENT=pg
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_DATABASE=database
      - DATABASE_USERNAME=username
      - DATABASE_PASSWORD=password
      - STRINGIFY_LOGS=true

  build-database:
    extends: base-database
    ports:
      - 5432
  build-application:
    extends: base-application
    links:
      - build-database:database
    environment:
      - ZIPKIN_RECODER=mute
      - STRINGIFY_LOGS=false
      - LOG_LEVEL=error
    ports:
      - 9000:9000

  development-database:
    extends: base-database
    ports:
      - 5432:5432
  development-application:
    extends: base-application
    command: gulp nodemon_development
    environment:
      - NODE_ENV=development
      - APPLICATION_DEBUG_PORT=7000
      - STRINGIFY_LOGS=false
    volumes:
      - .:/opt/application
    ports:
      - 9000:9000
      - 7000:7000
    links:
      - development-database:database

  codegen:
    image: 21stio/swagger-codegen:latest
    command: generate -i /opt/application/swagger.yml -l typescript-fetch -o /opt/application/sdk
    volumes:
      - .:/opt/application