version: '2'
services:

  base-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
  base-application:
    build: .
    image: mircoservice-lab_base:latest
    environment:
      - LOG_LEVEL=info
      - ZIPKIN_RECODER=console
      - SERVICE_PORT=9000
      - SERVICE_NAME=petstore
      - DATABASE_CLIENT=pg
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_DATABASE=database
      - DATABASE_USERNAME=username
      - DATABASE_PASSWORD=password
      - STRINGIFY_LOGS=true

  build-postgres:
    extends: base-postgres
    ports:
      - 5432
  build-application:
    extends: base-application
    links:
      - build-postgres:postgres
    environment:
      - ZIPKIN_RECODER=mute
      - STRINGIFY_LOGS=false
      - LOG_LEVEL=error

  development:
    extends: base
    command: gulp nodemon_development_up
    environment:
      - NODE_ENV=development
      - APPLICATION_DEBUG_PORT=7000
      - STRINGIFY_LOGS=false
    ports:
      - 9000:9000
      - 7000:7000
    links:
      - postgres:postgres
  test:
    extends: base
    command: gulp dredd_up
    environment:
      - ZIPKIN_RECODER=mute
      - STRINGIFY_LOGS=false
      - LOG_LEVEL=error
    links:
      - postgres:postgres
  codegen:
    build:
      context: .
      dockerfile: SwaggerCodegen.Dockerfile
    image: mircoservice-lab_swagger-codegen:latest
    command: java -jar swagger-codegen-cli.jar generate -i /opt/microservice-lab/swagger.yml -l typescript-fetch -o /opt/microservice-lab/sdk
    volumes:
      - .:/opt/microservice-lab