---
  swagger: "2.0"

  info: 
    version: "1.0.0"
    title: "Swagger Petstore"

  host: "petstore.swagger.io"
  basePath: "/v1"

  schemes: 
    - "http"
  consumes: 
    - "application/json"
  produces:
    - "application/json; charset=utf-8"


  parameters:
    Id:
      name: id
      in: path
      required: true
      x-example: 1
      type: integer
      format: int64
    PetBodyRequest:
      name: petBodyRequest
      in: body
      required: true
      schema:
        $ref: '#/definitions/IPetBodyRequest'
        example:
          name: Walter
          tag: dog


  responses:
    MessageResponse:
      description: message response
      schema:
        $ref: '#/definitions/IMessageResponse'
    PetResponse:
      description: pet response
      schema:
        $ref: '#/definitions/IPetResponse'
    PetsResponse:
      description: pets response
      schema:
        $ref: '#/definitions/IPetsResponse'


  paths: 
    /pets: 
      get:
        operationId: getPets
        responses: 
          200:
            $ref: '#/responses/PetsResponse'
      post:
        operationId: createPet
        parameters:
          - $ref: '#/parameters/PetBodyRequest'
        responses:
          200:
            $ref: '#/responses/MessageResponse'

    /pets/{id}:
      get:
        operationId: getPet
        parameters:
          - $ref: '#/parameters/Id'
            x-example: 1
        responses:
          200:
            $ref: '#/responses/PetResponse'
      put:
        operationId: updatePet
        parameters:
          - $ref: '#/parameters/Id'
            x-example: 2
          - $ref: '#/parameters/PetBodyRequest'
        responses:
          200:
            $ref: '#/responses/MessageResponse'
      delete:
        operationId: deletePet
        parameters:
          - $ref: '#/parameters/Id'
            x-example: 3
        responses:
          200:
            $ref: '#/responses/MessageResponse'


  definitions:
    $ref: swagger-definitions.yml
