---
  swagger: "2.0"
  info: 
    version: "1.0.0"
    title: "Swagger Petstore"
    description: "A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification"
    termsOfService: "http://swagger.io/terms/"
    contact: 
      name: "Swagger API Team"
    license: 
      name: "MIT"
  host: "petstore.swagger.io"
  basePath: "/v1"
  schemes: 
    - "http"
  consumes: 
    - "application/json"
  produces:
    - "application/json; charset=utf-8"
  paths: 
    /pets: 
      get: 
        description: "Returns all pets from the system that the user has access to"
        responses: 
          "200":
            description: "A list of pets."
            schema: 
              type: "array"
              items: 
                $ref: "#/definitions/GetPetResponse"
      post:
        description: Creates a new pet in the store.  Duplicates are allowed
        parameters:
          - name: pet
            in: body
            description: Pet to add to the store
            required: true
            schema:
              $ref: '#/definitions/CreatePetRequest'
              example:
                name: Walter
                tag: dog
        responses:
          "200":
            description: pet response
            schema:
              $ref: '#/definitions/GetPetResponse'
          default:
            description: unexpected error
            schema:
              $ref: '#/definitions/ErrorResponse'
    /pets/{id}:
      get:
        description: Returns a user based on a single ID, if the user does not have access to the pet
        parameters:
          - name: id
            in: path
            description: ID of pet to fetch
            required: true
            x-example: 1
            type: integer
            format: int64
        responses:
          "200":
            description: pet response
            schema:
              $ref: '#/definitions/GetPetResponse'
          default:
            description: unexpected error
            schema:
              $ref: '#/definitions/ErrorResponse'
      put:
        description: Updates a new pet in the store.  Duplicates are allowed
        parameters:
          - name: id
            in: path
            description: ID of pet to fetch
            required: true
            x-example: 1
            type: integer
            format: int64
          - name: pet
            in: body
            description: Pet to update in the store
            required: true
            schema:
              $ref: '#/definitions/CreatePetRequest'
              example:
                name: Walter
                tag: dog
        responses:
          "200":
            description: pet response
            schema:
              $ref: '#/definitions/GetPetResponse'
          default:
            description: unexpected error
            schema:
              $ref: '#/definitions/ErrorResponse'
      delete:
        description: Returns a user based on a single ID, if the user does not have access to the pet
        operationId: find pet by id
        parameters:
          - name: id
            in: path
            description: ID of pet to fetch
            required: true
            x-example: 1
            type: integer
            format: int64
        responses:
          "200":
            description: pet response
            schema:
              $ref: '#/definitions/GetPetResponse'
          default:
            description: unexpected error
            schema:
              $ref: '#/definitions/ErrorResponse'
  definitions: 
    $ref: swagger-definitions.yml
