services:
  microservice_lab_postgres:
    service_name: microservice-lab-postgres
    port: 5432
    database: microservice_lab
    username: peter
    password: peter123
  microservice_lab:
    service_name: microservice-lab
    service_port: 9000
    log_level: info
    zipkin_recorder: mute
    stringify_logs: "true"
    database_client: pg